baseurl = "https://blog.lemondouble.com"
title = "Lemon Blog"
defaultContentLanguage = "ko"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true

[pagination]
pagerSize = 10

[outputs]
home = ["HTML", "RSS", "JSON"]
