mainSections = ["post"]
rssFullContent = true
favicon = "https://cdn.lemondouble.com/homepage/favicon.ico"

[footer]
since = 2022
customText = "LemonDouble"

[dateFormat]
published = "2006.01.02"

[author]
name = "Lemon"
avatar = "/img/avatar.png"

[social]
github = "https://github.com/LemonDouble"
twitter = "https://twitter.com/_lemon_berry_"
email = "contact@lemondouble.com"
misskey = "https://sns.lemondouble.com/@lemondouble"

[comments]
enabled = true
provider = "giscus"

[comments.giscus]
repo = "LemonDouble/LemonDouble.github.io-comments"
repoID = "R_kgDOI0UkDA"
category = "Comments"
categoryID = "DIC_kwDOI0UkDM4CcIeY"
mapping = "pathname"
reactionsEnabled = 1
emitMetadata = 0
